// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace egresados {
	
	
	public partial class empresas {
		
		protected System.Web.UI.WebControls.Content MainContent;
		
		public new egresados.javeriana Master {
			get {
				return ((egresados.javeriana)(base.Master));
			}
		}
	}
}
